# Generated by Django 6.0.6 on 2026-07-09 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('idEmploye', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomEmploye', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenomEmploye', models.CharField(max_length=100, verbose_name='Prénom')),
                ('Fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('Email', models.EmailField(max_length=150, unique=True, verbose_name='Adresse Email')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomService', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('Localisation', models.CharField(max_length=150, verbose_name='Localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('idEquipement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codeInventaire', models.CharField(max_length=100, unique=True, verbose_name='Code Inventaire')),
                ('Designation', models.CharField(max_length=150, verbose_name='Désignation')),
                ('Marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('Modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('numSerie', models.CharField(max_length=100, unique=True, verbose_name='Numéro de Série')),
                ('dateAcquisition', models.DateField(verbose_name="Date d'Acquisition")),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur')),
                ('Etat', models.CharField(max_length=50, verbose_name="État de l'équipement")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='apps.categorie')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='apps.employe')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='apps.service')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('idAffectation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateAffectation', models.DateField(verbose_name="Date d'affectation")),
                ('dateRetour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='apps.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('idMaintenance', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateMaintenance', models.DateField(verbose_name='Date de la maintenance')),
                ('typeMaintenance', models.CharField(max_length=100, verbose_name='Type de maintenance')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Cout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='apps.equipement')),
            ],
        ),
    ]
